(in-package :nglview)

(defparameter +representation-names+
  '(("axes" . "axes")
    ("point" . "point")
    ("line" . "line")
    ("rope" . "rope")
    ("tube" . "tube")
    ("trace" . "trace")
    ("label" . "label")
    ("slice" . "slice")
    ("unitcell" . "unitcell")
    ("cartoon" . "cartoon")
    ("licorice" . "licorice")
    ("distance" . "distance")
    ("ribbon" . "ribbon")
    ("surface" . "surface")
    ("backbone" . "backbone")
    ("contact" . "contact")
    ("hyperball" . "hyperball")
    ("rocket" . "rocket")
    ("helixorient" . "helixorient")
    ("simplified_base" . "base")
    ("spacefill" . "spacefill")
    ("ball_and_stick" . "ball+stick")))

